### ISSUE TITLE
Generate static website

### ISSUE THREAD

**Issue by pocky** [LePetitBloc/LePetitBloc#4]
## Context

Our static website is buit on gh-pages with this npm task `"deploy": "gh-pages -d build",`. This is a not a true static website and it's bad for SEO.

We need something to generate this :). @lutangar will be the reviewer

**Comment by lutangar** [comment]
@JulesAaelio you can have a look at https://github.com/LePetitBloc/wallets for how it can be done with `gatsbyjs`.

And for the deploy process:
* https://docs.travis-ci.com/user/deployment/pages/
* https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/
